# Generated by Django 3.0.5 on 2021-05-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almabetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studmarks',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
