# Generated by Django 3.0.5 on 2021-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almabetter', '0002_auto_20210518_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='studmarks',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
