# Generated by Django 3.0.5 on 2021-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almabetter', '0003_studmarks_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='studmarks',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
